---
- name: Deploy {{ target }} 
  hosts: "{{ target }}"
  vars:
    ci_cd_namespace: jero-ci-cd
    dev_namespace: jero-dev
    test_namespace: jero-test
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier
